config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :cards, only: [:new, :create]
  end
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  has_rich_text :content
  broadcasts_to :list
  # after_create_commit -> { broadcast_append_to list }
  # after_destroy_commit -> { broadcast_remove_to list }
  # after_update_commit -> { broadcast_replace_to list }
end

app/models/list.rb
class List < ApplicationRecord
  has_rich_text :content
  has_many :cards, dependent: :destroy

  broadcasts
  # What Brodcast does:
  # after_create_commit -> { broadcast_append_to self }
  # after_destroy_commit -> { broadcast_remove_to self }
  # after_update_commit -> { broadcast_replace_to self }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_list

  def new
    @card = @list.cards.new
  end

  def create
    @card = @list.cards.create!(card_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @list }
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def card_params
    params.require(:card).permit(:content)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cards/_card.html.erb
<div class="card mb-2 d-flex flex-row p-2">
  <%= content_tag :div, id: dom_id(card) do %>
    <%= card.content %>
    <em>Card created <%= time_ago_in_words(card.created_at) %> ago</em>
  <% end %>
</div>

app/views/cards/new.html.erb
<%= turbo_frame_tag 'new_card' do %>
  <%= form_with model: [@list, @card] do |form| %>
      <div class='field'>
        <%= form.text_field :content %>
        <%= form.submit 'Add', 'data-reset_form-target': 'button' %>
      </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardHotwired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application.css' %>

    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.text_field :title, autofocus: true %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<%= content_tag :div, id: dom_id(list) do %>
  <h1>
    <%= list.title %>
  </h1>
<% end %>

app/views/lists/edit.html.erb
<%= turbo_frame_tag 'list' do %>

  <%= render 'form', list: @list %>

<% end %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Board Hotwired</h1>

  <div class="row">
    <% @lists.each do |list| %>
      <%= turbo_stream_from list %>

      <div class="col-3 card mr-5 bg-light font-weight-bold" id="<%= dom_id(list) %>">
        <h4 class="p-2"><%= list.title %></h4>
        <div>
          <% list.cards.each do |card| %>
            <div class="card mb-2 d-flex flex-row" id="<%= dom_id(card) %>">
              <div class="card-body">
                <h5 class="card-title"><%= card.content %></h5>
              </div>
            </div>
          <% end %>
        </div>
        <%= turbo_frame_tag 'new_card', src: new_list_card_path(list), target: :_top %>
      </div>
    <% end %>
  </div>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<%= turbo_frame_tag 'list' do %>

  <h1>New List</h1>

  <%= render 'form', list: @list %>

  <%= link_to 'Back', lists_path, 'data-turbo-frame': :_top %>

<% end %>

app/views/lists/show.html.erb
<div class="col-12 card mr-5 bg-light font-weight-bold">
  <%= turbo_stream_from @list %>

  <%= turbo_frame_tag 'list' do %>
    <%= link_to "Edit list title", edit_list_path(@list), class: 'text-decoration-none' %>
    <%= render @list %>
  <% end %>

  <div id='cards'>
    <%= render @list.cards %>
  </div>

  <%= turbo_frame_tag 'new_card', src: new_list_card_path(@list), target: :_top %>
</div>